client:
  delivery:
    url: ${CLIENT_DELIVERY_URL}

jwt:
  secret: ${COURIERS_TRACKING_JWT_SECRET}
  expirationInMillis: 86400000

spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:gadget-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: somepwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true